title: Computer Systems Security
description: ENEE 457-Computer Systems Security (Fall 2023)
theme: just-the-docs

url: https://charleslipku.github.io/umd-enee457/
search_enabled: true
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 10
search.button: true

callouts:
  note:
    title: Note
    color: purple


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

back_to_top: true
back_to_top_text: "Back to top"